"""empty message

Revision ID: 6f5e25018223
Revises: c514ce84f7a1
Create Date: 2023-06-17 09:08:47.656635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5e25018223'
down_revision = 'c514ce84f7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_poster')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_poster', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id_poster'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
