"""empty message

Revision ID: 8a328a04fb35
Revises: 70a188026ee8
Create Date: 2023-06-17 09:00:56.974832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a328a04fb35'
down_revision = '70a188026ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_country', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'country', ['id_country'], ['id'])
        batch_op.create_foreign_key(None, 'genre', ['genre'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_country')
        batch_op.drop_column('genre')
        batch_op.drop_column('date')
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
