"""empty message

Revision ID: c42eb50f466e
Revises: 4c8ddc85eb91
Create Date: 2023-06-17 09:10:44.970708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42eb50f466e'
down_revision = '4c8ddc85eb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id_poster', sa.Integer(), nullable=True),
    sa.Column('id_genre', sa.Integer(), nullable=True),
    sa.Column('id_country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_country'], ['country.id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['id_poster'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film')
    # ### end Alembic commands ###
