"""empty message

Revision ID: c514ce84f7a1
Revises: a9a716fe26b2
Create Date: 2023-06-17 09:07:35.114432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c514ce84f7a1'
down_revision = 'a9a716fe26b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_poster')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_poster', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id_poster'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
